### ISSUE TITLE
Are the integers in the array passed to the model bounded?

### ISSUE THREAD

**Issue by TylerRichie** [daring90808/ai-mathematician#1]
In the `fromDarin` function here:

https://github.com/daring90808/ai-mathematician/blob/master/src/conversion/Utilities.java#L49

you return an array of 96 integers. Are those integers bounded to a range?

**Comment by daring90808** [comment]
Yes. They are between 0 and 6 BUT 4 is considered empty. (In other words, you should never have your AI worry about setting something to a 4.) 5 and 6 are FIRE and SHARP respectively. Your AI should never need to set anything to either of these values either. Basically, your AI only needs to ever worry about setting a 4 value (EMPTY) to somewhere between 0 and 3.

**Comment by TylerRichie** [comment]
When you say "somewhere between 0 and 3," do you mean [0,3] or (0,3]?

**Comment by daring90808** [comment]
[0,3]
